name: test

on:
  push:
    branches:
      - "master"

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: make
      - run: yarn
      - run: yarn semantic-release
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
